cards/index.js
characters/index.js
monsters/base.js

makes decks always be 7 cards

---

game.js

fixes #31 
I'm going to bet that this is going to be more of a starting point. I don't quite grok the new channelManager yet, and I'm betting I'm sorely abusing or underutilizing either it or the emit system or both...

Gh31   end of battle xp and card should be shown to user

---

battlefield.js
characters/beastmaster.js
game.js
helpers/flavor.js
helpers/tense.js
monsters/index.js
ring/index.js

Gh24   adds call monster from ring

---

game.js
package.json
player-handbook.js

Adds command list to players handbook
Makes look at command more forgiving

Adds commands to players handbook

---

package-lock.json

`npm install -g npm@latest`
`rm -rf node_modules && npm install`
"big improvement in install times and fewer errors in production"
https://blog.heroku.com/node-habits-2017
https://docs.npmjs.com/files/package-lock.json
http://blog.npmjs.org/post/161276872334/npm5-is-now-npmlatest

Upgrades to npm 5 and runs npm install

---

characters/beastmaster.js
game.js
monsters/index.js

fixes #21 
Allows player to specify cards to equip monster with using comma separated list
depends on #38

Gh21   equip shortcut

---

game.js

matches on dm guide and dmg for dungeon masters guide

---

.eslintrc
battlefield.js
cards/index.js
characters/base.js
characters/beastmaster.js
characters/index.js
creatures/base.js
game.js
helpers/capitalize.js
helpers/card.js
monsters/index.js
package-lock.json
package.json

fixes #45 
@dbb I don't know why the save function error is occurring, but I'm swallowing it for the meantime (because otherwise the game is completely broken after the first fight)

Gh45   monsters should leave ring after battle

---

cards/base.js
cards/flee.js
cards/heal.js
cards/hit-harder.js
cards/hit.js
cards/index.js
cards/lucky-strike.js
cards/pound.js
cards/rehit.js
cards/revive.js
channel/index.js
characters/base.js
characters/beastmaster.js
characters/beastmaster.mocha.node.js
characters/index.js
creatures/base.js
game.js
game.mocha.node.js
helpers/classes.js
helpers/pause.js
monsters/base.js
monsters/basilisk.js
monsters/index.js
monsters/minotaur.js
monsters/weeping-angel.js
package-lock.json
package.json
ring/index.js

Add tests for the Beastmaster

---

cards/hit.js
creatures/base.js
game.js
helpers/flavor.js

Allow cards to override flavors

---

cards/base.js
cards/blast.js
cards/blast.mocha.node.js
cards/hit-harder.js
cards/lucky-strike.js
cards/pound.js
characters/beastmaster.js
helpers/flavor.js

Create a magical "blast" card

---

battlefield.js
cards/base.js
cards/blast.js
cards/blast.mocha.node.js
cards/enchanted-faceswap.js
cards/flee.js
cards/index.js
cards/scotch.js
cards/scotch.mocha.node.js
cards/vengeful-rampage.js
cards/vengeful-rampage.mocha.node.js
cards/whiskey-shot.js
cards/whiskey-shot.mocha.node.js
characters/beastmaster.js
creatures/base.js
game.js
helpers/coins.js
ring/index.js
ring/index.mocha.node.js

Also adds coins. Added a few tests to the ring, and tested this manually. Will also add tests to the fight loop soon.

Don't end a fight if two or more monsters are still alive

---

battlefield.js
cards/destroy.js
characters/beastmaster.js
characters/beastmaster.mocha.node.js
creatures/base.js
game.js
game.mocha.node.js
monsters/basilisk.mocha.node.js
monsters/index.js
package-lock.json
package.json
ring/index.js

Gh42   dead for negative bloodied

---

cards/hit-harder.js
cards/hit.js

I should have done 15 damage, not 12...

Take damage modifiers into account with max double damage for nat 20

---

characters/beastmaster.mocha.node.js
game.js

Look at monster in detail.

---

card-probabilities.js
cards/blast.js
cards/boost.js
cards/curse.js
cards/enchanted-faceswap.js
cards/fight-or-flight.js
cards/fists-of-virtue.js
cards/flee.js
cards/heal.js
cards/hit-harder.js
cards/hit.js
cards/kalevala.js
cards/lucky-strike.js
cards/random.js
cards/rehit.js
cards/revive.js
cards/scotch.js
cards/scotch.mocha.node.js
cards/vengeful-rampage.js
cards/vengeful-rampage.mocha.node.js
cards/whiskey-shot.mocha.node.js
cards/wooden-spear.js
helpers/card.js
package.json

*Beginner*
Flee: 6%
Random Play: 9%
Heal: 12%
Blast: 19%
Fight or Flight: 20%
Hit: 34%
*Level 1*
The Kalevala (1d4): 2%
Flee: 3%
Harden: 5%
Brain Drain: 5%
Soften: 5%
Random Play: 5%
Heal: 7%
Fists of Virtue: 7%
Enchanted Faceswap: 9%
Fight or Flight: 11%
Blast: 11%
Wooden Spear: 11%
Hit: 18%
*Level 2*
The Kalevala (1d4): 1%
Scotch: 2%
Flee: 2%
Brain Drain: 3%
Thick Skin: 4%
Random Play: 4%
Harden: 4%
Lucky Strike: 4%
Soften: 4%
Basic Shield: 4%
Whiskey Shot: 5%
Fists of Virtue: 5%
Heal: 5%
Enchanted Faceswap: 6%
Rehit: 6%
Hit Harder: 7%
Blast: 7%
Wooden Spear: 8%
Fight or Flight: 8%
Hit: 12%
*Level 3*
The Kalevala (1d4): 1%
Pound: 1%
Vengeful Rampage: 2%
Scotch: 2%
Flee: 2%
Random Play: 3%
Thick Skin: 3%
Basic Shield: 3%
Lucky Strike: 3%
Brain Drain: 3%
Soften: 4%
Harden: 4%
Whiskey …

Rebalance card probabilities

---

characters/base.js
monsters/base.js

Only sort copies of a deck

---

battlefield.js
cards/index.js
cards/pick-pocket.js
cards/pick-pocket.mocha.node.js
monsters/gladiator.js

Adds pick pocket card
Adds unit tests
Fixes spelling mistake

Pick pocket

---

cards/fight-or-flight.js
cards/flee.js
cards/kalevala.js
characters/index.js
creatures/base.js
helpers/bosses.js
helpers/bosses.mocha.node.js
ring/index.js

At the moment, however, they _will_ be able to flee with pick pocket and enchanted faceswap, this will just be a much more rare occurrence.

Prevents bosses from fleeing in most circumstances

---

game.js

(GH82) announce card drop in ring

---

cards/index.js

fixes initial deck

---

cards/brain-drain.mocha.node.js
cards/curse.js
cards/curse.mocha.node.js
creatures/base.js
game.js
helpers/difference.js
ring/index.js

When a curse amount hits the cap it overflows into HP.

Put caps on curse

---

cards/base.js
cards/blast.js
cards/boost.js
cards/curse.js
cards/fight-or-flight.js
cards/fists-of-villainy.js
cards/fists-of-virtue.js
cards/flee.js
cards/flee.mocha.node.js
cards/heal.js
creatures/base.js
game.js

Fixes #115 
Would probably be a good idea to also update the faceswap card to use this method instead of directly replacing effect.

Add a method for determining targets

---

battlefield.js
cards/index.js
monsters/index.js

allow no more than 4 copies of a card in a monster's hand.

Max card duplicates

---

cards/immobilize.js

makes immobilize display message on fail even if no hit

---

cards/forked-stick.mocha.node.js
cards/immobilize.js

(GH131) frees target it player dies after immobilizing them

---

cards/immobilize.js
cards/pick-pocket.js
cards/pick-pocket.mocha.node.js

 Fix targeting of the pick pocket card

---

creatures/base.js
monsters/basilisk.mocha.node.js

(GH148) do not allow dead monsters to be hit

---

cards/pick-pocket.js

This doesn't fix any issues with horn gore, but it does make pick pocket work better with cloaks / faceswaps.

Use the same mechanism as random for pick pocket

---

cards/helpers/is-matching.js
characters/base.js
characters/beastmaster.js
creatures/base.js
game.js
items/helpers/is-matching.js
items/index.js
items/store/sell.js
monsters/base.js

Next tasks will be adding prices to all existing cards, writing some tests, and creating the 'buy' portion of the store.

Add a store where you can sell cards and items

---

cards/base.js
helpers/chance.js

Moves strokeOfLuck and curseOfLoki determination into roll instead of checkSuccess

Moves strokeOfLuck and curseOfLoki to roll

---

battlefield.js
cards/cloak-of-invisibility.js
cards/heal.js
characters/beastmaster.js
creatures/base.js
helpers/experience.js
helpers/experience.mocha.node.js
monsters/base.js
ring/index.js

Limit battles to a max of 10 rounds, reduce invisibility max turns by 1, and reduce heal bonus each time a heal is played until the bonus hits zero, at which point it resets

Battles should end

---

cards/battle-focus.mocha.node.js
cards/berserk.js
cards/berserk.mocha.node.js

The fatigue calculation was all messed up, this fixes that.
Also renames "diminish" -> "fatigue" because that makes more sense.
Adds a bunch of unit tests, removes a redundant unit test.
Tried to make things more "functional" :)

Fix berserk

---

battlefield.js
cards/heal.js
cards/pick-pocket.mocha.node.js
characters/helpers/random.js
helpers/bosses.js
helpers/bosses.mocha.node.js
helpers/targeting-strategies.js
helpers/targeting-strategies.mocha.node.js
ring/index.js

Allows multiple bosses to be in the room at the same time, and won't start the fight if there are no human players in the ring even if there are multiple bosses. Bosses also won't target each other by default.

Allow battles with multiple bosses

---

announcements/effect.js
announcements/hit.js
cards/sandstorm.js
characters/base.js
characters/beastmaster.js
characters/helpers/hydrate.js
creatures/base.js
game.js
helpers/get-array.js
helpers/get-array.mocha.node.js
helpers/tense.js
items/base.js
items/helpers/choose.js
items/helpers/hydrate.js
items/helpers/transfer.js
items/helpers/transfer.mocha.node.js
items/index.js
items/scrolls/lottery-ticket.js
items/scrolls/lottery-ticket.mocha.node.js
monsters/base.js
monsters/helpers/equip.js
monsters/helpers/hydrate.js

Allow hydration of items and transfer of items between creatures (in particular, between a character and their monsters). Also adds a lottery ticket as an example of something that can be used by a character rather than a monster.

Initial items PR

---

cards/cloak-of-invisibility.js
characters/base.js
characters/helpers/create.js
creatures/base.js
game.js
helpers/card.js
helpers/classes.js
monsters/base.js
package.json

Needed for ease of item testing. Also cleans up the character creation script.

Add the ability to look at and edit characters

---

announcements/modifier.js
cards/brain-drain.js
cards/coil.js
creatures/base.js
items/potions/chocolate-bar.js
items/potions/healing.js
items/potions/helpers/all.js
items/potions/swiss-chocolate.js

These are only usable on live monsters. I want to create a revive potion that is usable on dead monsters - a cheap one for when you're not in an encounter and an expensive (and less powerful one) that is usable in encounters as well.

 Add a couple of healing potions

---

cards/prion-disease.mocha.node.js
characters/helpers/random.js
creatures/base.js
helpers/bosses.js
helpers/targeting-strategies.js
helpers/teams.js
items/scrolls/helpers/all.js
items/scrolls/sorting-hat.js
items/scrolls/sorting-hat.mocha.node.js

Also display the team in a creature's description.

Makes it possible to join a team

---

game.js
monster-manual.js

Opens the door for adding a MD generator.

Allow the monster manual to be generated for other formats

---

cards/base.js
cards/blink.mocha.node.js
cards/delayed-hit.js
cards/enchanted-faceswap.mocha.node.js
cards/forked-metal-rod.mocha.node.js
cards/horn-gore.mocha.node.js
cards/mesmerize.mocha.node.js
cards/pick-pocket.js
cards/pick-pocket.mocha.node.js
cards/random.js
cards/sandstorm.mocha.node.js
cards/test.js
ring/index.js

Makes random card and pick pocket much cleaner and makes tests much more realistic.

Move encounter effects into the card
